import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as Y from 'yjs';
import { applyOperation, initialData, textDocument, toBase64, importData } from '../src/utils/collaboration/protocol';
import { canonical,readableBoard,boardCsv } from '../src/utils/collaboration/export';
import { NoteText } from '../src/utils/collaboration/text';
import type { Resource,Operation } from '../src/types/collaboration';
const resource=(kind:'board'|'drawing'='board'):Resource=>({id:crypto.randomUUID(),workspace_id:crypto.randomUUID(),kind,name:'Team',revision:1,generation:1,deleted_at:null,updated_at:new Date().toISOString(),data:initialData(kind)});
const op=(r:Resource,type:string,payload:any):Operation=>({id:crypto.randomUUID(),resourceId:r.id,generation:r.generation,type,payload,createdAt:new Date().toISOString()});
function board(){const r=resource();return applyOperation(r,op(r,'note.create',{id:'note',columnId:r.data.columns[0].id}));}
test('simultaneous Yjs text updates merge independently of arrival order',()=>{
 const r=board(),a=textDocument(),b=textDocument();a.getText('body').insert(0,'Editor A');b.getText('body').insert(0,'Editor B');
 const oa=op(r,'note.text',{id:'note',generation:1,update:toBase64(Y.encodeStateAsUpdate(a))}),ob=op(r,'note.text',{id:'note',generation:1,update:toBase64(Y.encodeStateAsUpdate(b))});
 const first=applyOperation(applyOperation(r,oa),ob),second=applyOperation(applyOperation(r,ob),oa);assert.equal(first.data.notes[0].body,second.data.notes[0].body);assert.match(first.data.notes[0].body,/Editor A/);assert.match(first.data.notes[0].body,/Editor B/);a.destroy();b.destroy();
});
test('metadata conflict does not overwrite current title',()=>{const r=board(),payload={id:'note',generation:1,field:'title',value:'First',baseVersion:0};const changed=applyOperation(r,op(r,'note.field',payload));assert.throws(()=>applyOperation(changed,op(r,'note.field',{...payload,value:'Second'})),/changed/);assert.equal(changed.data.notes[0].title,'First');});
test('delete, restore and generation checks prevent stale resurrection',()=>{let r=board();r=applyOperation(r,op(r,'note.delete',{id:'note',generation:1}));assert.throws(()=>applyOperation(r,op(r,'note.field',{id:'note',generation:1,field:'color',value:'pink',baseVersion:0})),/deleted/);r=applyOperation(r,op(r,'note.restore',{id:'note',generation:1}));assert.equal(r.data.notes[0].generation,2);assert.throws(()=>applyOperation(r,op(r,'note.delete',{id:'note',generation:1})),/changed/);const stale=op(r,'resource.rename',{name:'Stale',baseName:r.name});r=applyOperation(r,op(r,'resource.delete',{}));r=applyOperation(r,op(r,'resource.restore',{}));assert.throws(()=>applyOperation(r,stale),/generation/);});
test('occupied column deletion requires handling and moves atomically',()=>{const r=board(),id=r.data.columns[0].id;assert.throws(()=>applyOperation(r,op(r,'column.delete',{id})),/Choose/);const changed=applyOperation(r,op(r,'column.delete',{id,action:'move',targetId:r.data.columns[1].id}));assert.ok(changed.data.columns[0].deletedAt);assert.equal(changed.data.notes[0].columnId,r.data.columns[1].id);assert.equal(r.data.notes[0].columnId,id);});
test('drawing concurrent additions survive and stale same-element writes conflict',()=>{let r=resource('drawing');const element={id:'a',version:1,versionNonce:1,isDeleted:false,type:'rectangle',x:0,y:0,width:40,height:40};r=applyOperation(r,op(r,'drawing.change',{changes:[{element,baseVersion:0}]}));r=applyOperation(r,op(r,'drawing.change',{changes:[{element:{...element,id:'b'},baseVersion:0}]}));assert.equal(r.data.elements.length,2);assert.throws(()=>applyOperation(r,op(r,'drawing.change',{changes:[{element:{...element,version:2},baseVersion:0}]})),/concurrently/);r=applyOperation(r,op(r,'drawing.change',{changes:[{element:{...element,version:2,isDeleted:true},baseVersion:1}]}));assert.throws(()=>applyOperation(r,op(r,'drawing.change',{changes:[{element:{...element,version:3},baseVersion:2}]})),/explicit/);});
test('image references require durable files and canonical snapshots retain tombstones',()=>{const r=resource('drawing'),element={id:'image',version:1,versionNonce:1,isDeleted:false,type:'image',fileId:'file',x:0,y:0,width:40,height:40};assert.throws(()=>applyOperation(r,op(r,'drawing.change',{changes:[{element,baseVersion:0}]})),/Image/);const files={file:{id:'file',mimeType:'image/png',dataURL:'data:image/png;base64,aGVsbG8=',created:1}};const saved=applyOperation(r,op(r,'drawing.change',{changes:[{element,baseVersion:0}],files}));assert.deepEqual((canonical(saved) as any).files,files);});
test('card and sidebar share a text model and apply minimal local edits',()=>{const r=board(),updates:string[]=[];const model=new NoteText(r.data.notes[0],u=>updates.push(u));let calls=0;model.subscribe(()=>calls++);model.replace('hello');model.replace('hello world');assert.equal(model.snapshot(),'hello world');assert.equal(updates.length,2);assert.equal(calls,2);model.destroy();});
test('canonical imports rebuild text state and reject hostile dimensions/links',()=>{const r=board();r.data.notes[0].body='Recovered';const recovered=importData('board',r.data);assert.equal(textDocument(recovered.notes[0]).getText('body').toString(),'Recovered');assert.throws(()=>importData('drawing',{elements:[{id:'bad',version:1,versionNonce:1,x:NaN,y:0,width:1,height:1}],files:{}}),/dimensions/);});
test('readable exports escape HTML and spreadsheet formulas',()=>{const r=board();r.name='<script>';r.data.notes[0].title='=RUN()';r.data.notes[0].body='<img onerror=alert(1)>';assert.ok(!readableBoard(r).includes('<img onerror'));assert.match(boardCsv(r),/'=RUN/);});
