import { chromium } from '@playwright/test';
import { mkdir,writeFile } from 'node:fs/promises';
import os from 'node:os';
const browser=await chromium.launch({channel:'chrome'}),page=await browser.newPage({viewport:{width:1440,height:900}}),results:any[]=[];
await page.addInitScript('window.__name = (fn) => fn;');
await page.addInitScript(()=>{(window as any).profileLongTasks=[];new PerformanceObserver(list=>{for(const entry of list.getEntries())(window as any).profileLongTasks.push({start:entry.startTime,duration:entry.duration});}).observe({type:'longtask',buffered:true});});
const measure=async()=>page.evaluate(async()=>{const frames:number[]=[];const begin=performance.now();let previous=begin;await new Promise<void>(resolve=>{const tick=(now:number)=>{frames.push(now-previous);previous=now;const column=document.querySelector('.kanban-scroll');if(column)column.scrollTop=(now-begin)%1400;if(now-begin<2500)requestAnimationFrame(tick);else resolve();};requestAnimationFrame(tick);});frames.sort((a,b)=>a-b);return {frames:frames.length,p50:frames[Math.floor(frames.length*.5)],p95:frames[Math.floor(frames.length*.95)],over16_7:frames.filter(t=>t>16.7).length,over33_3:frames.filter(t=>t>33.3).length,longTasks:(window as any).profileLongTasks,heapBytes:(performance as any).memory?.usedJSHeapSize,renderedNotes:document.querySelectorAll('.sticky-note').length,userAgent:navigator.userAgent};});
try{
for(const count of [100,1000,5000])for(const columns of [3,10]){
 const fixture=await page.request.post('http://127.0.0.1:5191/api/fixture-profile',{headers:{Authorization:'Bearer fixture:admin'},data:{count,columns}});const dataset=await fixture.json();const start=Date.now();await page.goto('http://127.0.0.1:5191/kanban/11111111-1111-4111-8111-111111111111');await page.getByRole('heading',{name:'Laboratory priorities',exact:true}).waitFor();results.push({kind:'board',count,columns,dataset,loadMs:Date.now()-start,...await measure()});
}
for(const count of [100,1000,5000]){
 await page.goto('http://127.0.0.1:5191/spike');await page.waitForFunction(()=>Boolean((window as any).editorAPI));const start=Date.now();const bytes=await page.evaluate(count=>{const w=window as any;const elements=w.spike.make(Array.from({length:count},(_,i)=>({type:i%2?'ellipse':'rectangle',id:`profile-${i}`,x:(i%100)*70,y:Math.floor(i/100)*60,width:50,height:40})));w.spike.setRemote(elements);return JSON.stringify(elements).length;},count);await page.waitForFunction(count=>(window as any).editorAPI.getSceneElements().length===count,count);results.push({kind:'drawing',count,bytes,reconcileMs:Date.now()-start,...await measure()});
}
await mkdir('design/validation',{recursive:true});await writeFile('design/validation/collaboration-profile.json',JSON.stringify({conditions:{platform:os.platform(),osRelease:os.release(),cpu:os.cpus()[0]?.model,cpuCount:os.cpus().length,totalMemory:os.totalmem(),browser:browser.version(),viewport:{width:1440,height:900},headless:true,throttling:'none',data:'synthetic; boards contain 107-character bodies and shared Yjs seed state; drawings contain rectangles/ellipses without images',limitations:'Single-column scroll/render sample; drawing samples are idle after reconciliation. Load/reconciliation long tasks included; no claim about physical mobile devices, all-user hardware, production latency, or active drawing/drag gesture frame timing.'},results},null,2));console.log(results.map(r=>({kind:r.kind,count:r.count,columns:r.columns,p95:r.p95,longTasks:r.longTasks.length,renderedNotes:r.renderedNotes,bytes:r.dataset?.bytes||r.bytes})));
}finally{await browser.close();}
