// Run in Figma through use_figma. All screens consist of editable layers.
await Promise.all(['Regular','Medium','Semi Bold'].map(style=>figma.loadFontAsync({family:'Inter',style})));
const page=figma.createPage();page.name='02 · Screens / desktop & mobile';await figma.setCurrentPageAsync(page);
const allVariables=await figma.variables.getLocalVariablesAsync();
const collections=await figma.variables.getLocalVariableCollectionsAsync();
const themes={};for(const theme of ['Light','Dark']){const collection=collections.find(c=>c.name==='Precision Lab / '+theme);themes[theme]=Object.fromEntries(allVariables.filter(v=>v.variableCollectionId===collection.id).map(v=>[v.name.slice(6),v]));}
const components={};for(const [name,id] of Object.entries({primary:'3:38',secondary:'3:40',metric:'3:42',input:'3:46',nav:'3:49',status:'3:51'}))components[name]=await figma.getNodeByIdAsync(id);
let theme='Light';const output=[];const targets={};const buttons=[];
function paint(token){const v=themes[theme][token];const col=collections.find(c=>c.id===v.variableCollectionId);return figma.variables.setBoundVariableForPaint({type:'SOLID',color:v.valuesByMode[col.defaultModeId]},'color',v);}
function box(parent,name,width,fill='surface',direction='VERTICAL',padding=16,gap=12){const n=figma.createAutoLayout(direction);n.name=name;n.resize(width,100);n.primaryAxisSizingMode=direction==='HORIZONTAL'?'FIXED':'AUTO';n.counterAxisSizingMode=direction==='HORIZONTAL'?'AUTO':'FIXED';n.paddingTop=padding;n.paddingBottom=padding;n.paddingLeft=padding;n.paddingRight=padding;n.itemSpacing=gap;n.cornerRadius=12;n.fills=fill?[paint(fill)]:[];if(fill)n.strokes=[paint('border')];parent.appendChild(n);return n;}
function text(parent,value,size=14,token='text',weight='Regular',width){const n=figma.createText();n.fontName={family:'Inter',style:weight};n.fontSize=size;n.characters=value;n.fills=[paint(token)];parent.appendChild(n);if(width){n.textAutoResize='HEIGHT';n.resize(width,Math.max(size*1.5,20));}return n;}
function instance(parent,key,label,width){const n=components[key].createInstance();parent.appendChild(n);if(width)n.resize(width,n.height);const fonts=n.findAllWithCriteria({types:['TEXT']});if(label){if(key==='primary'||key==='secondary'){const property=Object.keys(n.componentProperties).find(k=>k.startsWith('Label'));n.setProperties({[property]:label});}else if(fonts[0])fonts[0].characters=label;}
 const nodes=[n,...n.findAll()];for(const node of nodes){if('fills'in node&&Array.isArray(node.fills)){node.fills=node.fills.map(p=>{const alias=p.boundVariables?.color;const old=alias?allVariables.find(v=>v.id===alias.id):null;return old?paint(old.name.slice(6)):p;});}if('strokes'in node&&Array.isArray(node.strokes)){node.strokes=node.strokes.map(p=>p.boundVariables?.color?paint('border'):p);}}
 return n;}
const navs=[['Dashboard','dashboard'],['New sample','new'],['Offline queue','queue'],['History','history'],['Incubations','incubation'],['Calendar','calendar'],['Live sheet','live'],['Logbook','logbook'],['Reports','results'],['Settings','settings']];
const specs=[
 ['dashboard','Dashboard','Your lab, in focus.','Every sample, every step, in one place.'],
 ['new','New sample','Log a new sample','Choose a sample type to begin logging.'],
 ['envi','ENVI sample','Environment / ENVI','Environmental swabs and bulk sample intake.'],
 ['water','WATER sample','Water sample','Process water logging.'],
 ['rawmats','RawMats sample','Materials, FG & SFG','Raw materials and finished goods logging.'],
 ['air','AIR sample','Air monitoring','Air quality and settling plate intake.'],
 ['queue','Offline queue','Your offline queue','Saved submissions waiting to synchronize.'],
 ['history','History','Every sample, recorded','Control numbers, status, and available reports.'],
 ['live','Live sheet','Your live lab records','Search, sort, and review protected sheet records.'],
 ['logbook','Logbook','The lab logbook','Organize records by sample type, analyst, and date.'],
 ['results','Reports','Results & reports','Review readings, update records, and generate reports.'],
 ['incubation','Incubations','Keep every reading on time','Due, overdue, and upcoming readings.'],
 ['calendar','Calendar','Your reading schedule','Incubation reading dates by analyst.'],
 ['settings','Settings','Workspace settings','Appearance, personnel, and protected configuration.'],
 ['login','Login','Your lab starts here.','Unilever QC Microbiology / Sample Logger'],
];
function scientific(parent,width=200){const n=figma.createNodeFromSvg('<svg xmlns="http://www.w3.org/2000/svg" width="240" height="180" viewBox="0 0 240 180"><g fill="none" stroke="#245bd6" stroke-width="2"><circle cx="120" cy="90" r="74" stroke-dasharray="3 8" opacity=".2"/><path d="M40 105L82 52L140 68L194 40M82 52L103 127L171 139L140 68M103 127L40 105M171 139L211 102L140 68"/><circle cx="40" cy="105" r="8"/><circle cx="82" cy="52" r="8"/><circle cx="140" cy="68" r="13"/><circle cx="194" cy="40" r="8"/><circle cx="103" cy="127" r="8"/><circle cx="171" cy="139" r="8"/><circle cx="211" cy="102" r="8"/></g></svg>');parent.appendChild(n);n.name='Scientific molecular vector';n.resize(width,width*.75);return n;}
function record(parent,label,id,status,width,mobile){const row=box(parent,'Record '+id,width,'surface',mobile?'VERTICAL':'HORIZONTAL',14,12);text(row,label,13,'text','Medium',mobile?width-28:Math.max(180,(width-80)*.45));text(row,id,11,'muted');instance(row,'status',status,145);return row;}
function intake(parent,w){for(const [label,key,detail]of [['Environment','envi','Surfaces & swabs'],['Water','water','Sources & sampling points'],['Materials','rawmats','Raw materials, FG & SFG'],['Air monitoring','air','Air quality & settling plates']]){const row=box(parent,label,w,'surface','VERTICAL',16,6);text(row,label,14,'text','Semi Bold');text(row,detail,11,'muted');const b=instance(row,'secondary','Log '+label,170);buttons.push({id:b.id,dest:key});}}
for(const [variant,index]of [['Light desktop',0],['Dark desktop',1],['Light mobile',2],['Dark mobile',3]]){
 theme=variant.startsWith('Dark')?'Dark':'Light';const mobile=variant.includes('mobile');const width=mobile?390:1440;
 for(const [screenIndex,[key,title,heading,description]]of specs.entries()){
 const root=box(page,variant+' / '+title,width,'background','HORIZONTAL',0,0);root.cornerRadius=0;root.x=100+index*1600;root.y=100+screenIndex*1900;root.clipsContent=false;
 const targetKey=variant+'/'+key;targets[targetKey]=root.id;
 if(!mobile&&key!=='login'){const side=box(root,'Sidebar',248,'surface','VERTICAL',24,12);text(side,'Unilever',25,'text','Semi Bold');text(side,'QC MICRO / SAMPLE LOGGER',9,'muted');for(const [label,dest]of navs){const link=instance(side,'nav',label,200);buttons.push({id:link.id,dest,variant});}text(side,'QC microbiology',12,'teal');text(side,'Sign out',12,'secondary');}
 const available=mobile?390:key==='login'?1440:1192;const main=box(root,'Main content',available,null,'VERTICAL',mobile?16:32,24);
 const w=available-(mobile?32:64);const header=box(main,'Header',w,'surface','HORIZONTAL',16,16);text(header,title,17,'text','Semi Bold');text(header,'Connected / Light · Dark · System',mobile?9:11,'muted');
 const hero=box(main,'Page introduction',w,'hero','VERTICAL',mobile?20:24,12);text(hero,'MICROBIOLOGY WORKSPACE',9,'teal','Medium');text(hero,heading,mobile?28:36,'text','Semi Bold',w-(mobile?40:48));text(hero,description,12,'secondary','Regular',w-(mobile?40:48));
 if(key==='dashboard'){const b=instance(hero,'primary','New sample',160);buttons.push({id:b.id,dest:'new',variant});const sync=instance(hero,'secondary','Sync records',160);buttons.push({id:sync.id,dest:'sync',variant});scientific(hero,mobile?110:220);
 const metricContainer=box(main,'Metrics',w,null,mobile?'VERTICAL':'HORIZONTAL',0,16);for(const [label,value,detail]of [['Recent logs','24','Latest 50 records'],['Pending sync','2','Queued & failed submissions'],['In progress','8','Within recent records'],['Awaiting review','3','Within recent records']]){const metric=instance(metricContainer,'metric',label,mobile?w:(w-48)/4);const texts=metric.findAllWithCriteria({types:['TEXT']});texts[1].characters=value;texts[2].characters=detail;}
 const activity=box(main,'Recent activity',w,'surface','VERTICAL',16,10);text(activity,'Recent activity',18,'text','Semi Bold');for(const [name,id,status]of [['Surface swab A','DEMO-001','In progress'],['Water point A','DEMO-002','Awaiting review'],['Material lot A','DEMO-003','Completed']])record(activity,name,id,status,w-32,mobile);const intakePanel=box(main,'Quick intake',w,'surface','VERTICAL',16,10);text(intakePanel,'Log a sample',18,'text','Semi Bold');intake(intakePanel,w-32);
 }else if(key==='new'){intake(main,w);
 }else if(['envi','water','rawmats','air'].includes(key)){const fields={envi:['Date Sampled','Time Sampled','Select categories','Select swab points','Swabbed By','Date Analyzed','Analyzed By','Status','Remarks'],water:['Date Sampled','Time Sampled','Water Source','Sampled By','Date Analyzed','Analyzed By','Status','Remarks'],rawmats:['Date Received / Sampled','Time','RFAF','Batch #','Type','Sample','Unit','Quantity','Source','Received By','Date Analyzed','Analyzed By','Status','Remarks'],air:['Date Performed','Time','Method','Sampling points','Performed By','Status','Remarks']}[key];const form=box(main,'Sample form',w,'surface','VERTICAL',24,16);for(const name of fields){const input=instance(form,'input',name,w-48);input.findAllWithCriteria({types:['TEXT']})[1].characters=name==='Status'?'ONGOING':'Select or enter value';}const submit=instance(form,'primary','Submit sample',180);buttons.push({id:submit.id,dest:'success',variant});
 }else if(key==='queue'){record(main,'Water point A','DEMO-001','Queued',w,mobile);record(main,'Air monitoring point A','DEMO-002','Failed',w,mobile);instance(main,'primary','Retry all (2)',180);
 }else if(['history','live','logbook','results'].includes(key)){const filters=box(main,'Filters',w,'surface',mobile?'VERTICAL':'HORIZONTAL',16,16);text(filters,'ENVI / WATER / RawMats / AIR',12,'blue');text(filters,'All analysts / Search records',12,'secondary');for(let i=1;i<=4;i++)record(main,['Surface swab A','Water point A','Material lot A','Air monitoring point A'][i-1],'DEMO-00'+i,i===2?'Completed':'In progress',w,mobile);instance(main,'secondary',key==='results'?'Generate report':'Column settings',180);text(main,'50 rows / Page 1 / Previous · Next',11,'muted');
 }else if(key==='incubation'){for(const section of ['Due today','Overdue','Upcoming readings']){const panel=box(main,section,w,'surface','VERTICAL',16,12);text(panel,section,18,'text','Semi Bold');const row=record(panel,'Surface swab A / Final (2D)','DEMO-001','In progress',w-32,mobile);buttons.push({id:row.id,dest:'results',variant});}
 }else if(key==='calendar'){text(main,'Month / Week / Day / Agenda · All analysts',12,'secondary');const calendar=box(main,'Month grid',w,'surface','VERTICAL',16,8);text(calendar,'October 2026',20,'text','Semi Bold');text(calendar,'Sun    Mon    Tue    Wed    Thu    Fri    Sat',mobile?10:14,'muted');for(let week=0;week<5;week++){const row=box(calendar,'Week '+week,w-32,null,'HORIZONTAL',0,8);for(let day=0;day<7;day++){const cell=box(row,'Day '+(week*7+day+1),(w-80)/7,'surface','VERTICAL',4,4);text(cell,String(week*7+day+1),11);if(day===3)text(cell,'Reading',mobile?7:10,'teal');}}
 }else if(key==='settings'){for(const title of ['Protected configuration','Appearance','Personnel lists','Google Sheets connection','Data management']){const panel=box(main,title,w,'surface','VERTICAL',16,12);text(panel,title,16,'text','Semi Bold');instance(panel,'secondary',title==='Appearance'?'Light / Dark / System':'Manage '+title,Math.min(w-32,300));}
 }else if(key==='login'){const login=box(main,'Sign in',Math.min(w,450),'surface','VERTICAL',24,16);instance(login,'input','Username',Math.min(w-48,400));instance(login,'input','Password',Math.min(w-48,400));instance(login,'primary','Sign in',180);instance(login,'secondary','Use PIN',180);instance(login,'secondary','Continue with Google',220);}
 if(mobile&&key!=='login'){const bottom=box(main,'Mobile navigation',w,'surface','HORIZONTAL',8,12);for(const [label,dest]of [['Home','dashboard'],['History','history'],['New','new'],['Queue','queue'],['Menu','settings']]){const item=text(bottom,label,11,dest===key?'blue':'secondary');buttons.push({id:item.id,dest,variant});}}
 text(main,'DESIGN PREVIEW / SYNTHETIC DATA',9,'muted');output.push({id:root.id,name:root.name,width:root.width,height:root.height,editableText:root.findAllWithCriteria({types:['TEXT']}).length});
 }
}
for(const item of buttons){const node=await figma.getNodeByIdAsync(item.id);const variant=item.variant||'Light desktop';const destination=targets[variant+'/'+item.dest];let ancestor=node;while(ancestor.parent && ancestor.parent.type!=="PAGE")ancestor=ancestor.parent;if(destination && ancestor.id!==destination)await node.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[{type:'NODE',destinationId:destination,navigation:'NAVIGATE',transition:{type:'DISSOLVE',duration:.24,easing:{type:'EASE_OUT'}},preserveScrollPosition:false}]}]);}
return {pageId:page.id,screens:output,targets,linkedControls:buttons.filter(b=>targets[(b.variant||'Light desktop')+'/'+b.dest]).length};
