import { useEffect,useMemo,useRef,useState,useCallback,memo } from 'react';
import { DndContext,PointerSensor,KeyboardSensor,useSensor,useSensors,useDroppable,closestCorners,DragOverlay } from '@dnd-kit/core';
import { SortableContext,useSortable,sortableKeyboardCoordinates } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { useReducedMotion } from 'framer-motion';
import { useVirtualizer } from '@tanstack/react-virtual';
import { Plus,X,Trash2,ArrowLeft,ArrowRight,ArrowUp,ArrowDown,Settings2,RotateCcw } from 'lucide-react';
import type { Column,Note,Resource } from '../../types/collaboration';
import { NoteText } from '../../utils/collaboration/text';
import CollaborativeBody from './CollaborativeBody';
import { useDialogFocus } from '../../hooks/useDialogFocus';
type Submit=(type:string,payload:Record<string,any>)=>Promise<unknown>;
const colors=['yellow','blue','green','pink'] as const;
const StickyNote=memo(function StickyNote({note,model,editable,select}:{note:Note;model:NoteText;editable:boolean;select:(id:string)=>void}) {
  const drag=useSortable({id:note.id,disabled:!editable});
  return <article ref={drag.setNodeRef} className={`sticky-note note-${note.color} ${drag.isDragging?'dragging':''}`} style={{transform:CSS.Transform.toString(drag.transform),transition:drag.isSorting?drag.transition:undefined}}>
    <div className="sticky-header"><button ref={drag.setActivatorNodeRef} className="sticky-drag-header" {...drag.attributes} {...drag.listeners} disabled={!editable} aria-label={`Move ${note.title}`}><strong>{note.title}</strong></button><button onClick={()=>select(note.id)} aria-label={`Settings for ${note.title}`}><Settings2 size={16}/></button></div><CollaborativeBody model={model} label={`Body of ${note.title}`} readOnly={!editable}/>
  </article>;
});
function ColumnView({column,notes,models,editable,submit,select,selected,active}:{column:Column;notes:Note[];models:(note:Note)=>NoteText;editable:boolean;submit:Submit;select:(id:string)=>void;selected?:string;active?:string}) {
  const {setNodeRef,isOver}=useDroppable({id:column.id}),scroll=useRef<HTMLDivElement>(null),section=useRef<HTMLElement|null>(null),[visible,setVisible]=useState(false),[editing,setEditing]=useState(false),[title,setTitle]=useState(column.title);
  useEffect(()=>{const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{rootMargin:'0px 100px'});if(section.current)observer.observe(section.current);return()=>observer.disconnect();},[]);
  const enabled=visible||notes.some(n=>n.id===selected||n.id===active);
  const setSection=useCallback((node:HTMLElement|null)=>{section.current=node;setNodeRef(node);},[setNodeRef]);
  const virtual=useVirtualizer({count:enabled?notes.length:0,getScrollElement:()=>scroll.current,estimateSize:()=>210,overscan:5,getItemKey:index=>notes[index].id,rangeExtractor:range=>{if(!enabled)return [];const ids=new Set<number>();for(let i=Math.max(0,range.startIndex-5);i<=Math.min(notes.length-1,range.endIndex+5);i++)ids.add(i);for(const id of [selected,active]){const index=notes.findIndex(n=>n.id===id);if(index>=0)ids.add(index);}return [...ids].sort((a,b)=>a-b);}});
  return <section ref={setSection} id={`column-${column.id}`} className={`kanban-column ${isOver?'drop-target':''}`} aria-label={column.title}>
    <header>{editing?<form onSubmit={e=>{e.preventDefault();void submit('column.rename',{id:column.id,title,baseTitle:column.title});setEditing(false);}}><input aria-label="Column name" value={title} onChange={e=>setTitle(e.target.value)} maxLength={200}/><button>Save</button></form>:<><h2>{column.title}</h2><span>{notes.length}</span>{editable&&<button onClick={()=>{setTitle(column.title);setEditing(true);}} aria-label={`Rename ${column.title}`}><Settings2 size={16}/></button>}</>}</header>
    <SortableContext items={notes.map(n=>n.id)}><div className="kanban-scroll" ref={scroll}><div className="virtual-notes" style={{height:virtual.getTotalSize()}}>{virtual.getVirtualItems().map(item=>{const note=notes[item.index];return <div key={note.id} data-index={item.index} ref={virtual.measureElement} style={{position:'absolute',top:item.start,width:'100%',paddingBottom:16}}><StickyNote note={note} model={models(note)} editable={editable} select={select}/></div>;})}</div></div></SortableContext>
    {editable&&<button className="kanban-add" onClick={()=>void submit('note.create',{id:crypto.randomUUID(),columnId:column.id,title:'New note'})}><Plus size={16}/>Add note</button>}
  </section>;
}
export default function KanbanBoard({resource,editable,submit}:{resource:Resource;editable:boolean;submit:Submit}) {
  const reduced=useReducedMotion();
  const columns=resource.data.columns.filter(c=>!c.deletedAt),notes=resource.data.notes.filter(n=>!n.deletedAt),[selected,setSelected]=useState<string>(),[active,setActive]=useState<string>(),[announcement,setAnnouncement]=useState(''),[columnTitle,setColumnTitle]=useState(''),[manage,setManage]=useState(false),[trash,setTrash]=useState(false),[lastDeleted,setLastDeleted]=useState<Note>(),[title,setTitle]=useState(''),[titleDirty,setTitleDirty]=useState(false),baseTitle=useRef(0),[deleteColumn,setDeleteColumn]=useState<Column>(),[deleteAction,setDeleteAction]=useState('move'),[target,setTarget]=useState('');
  const dialog=useRef<HTMLDivElement>(null);useDialogFocus(dialog,Boolean(deleteColumn),()=>setDeleteColumn(undefined));
  const models=useRef(new Map<string,NoteText>()),submitRef=useRef(submit);submitRef.current=submit;
  const getModel=(note:Note)=>{const key=note.id+':'+note.generation;let model=models.current.get(key);if(!model){model=new NoteText(note,update=>void submitRef.current('note.text',{id:note.id,generation:note.generation,update}));models.current.set(key,model);}return model;};
  useEffect(()=>{for(const n of notes)models.current.get(n.id+':'+n.generation)?.merge(n);},[resource.data.notes]);
  useEffect(()=>()=>{for(const model of models.current.values())model.destroy();},[]);
  const note=notes.find(n=>n.id===selected);
  useEffect(()=>{setTitleDirty(false);setTitle(note?.title||'');baseTitle.current=note?.versions.title||0;},[selected]);
  useEffect(()=>{if(note&&!titleDirty){setTitle(note.title);baseTitle.current=note.versions.title;}},[note?.title,note?.versions.title,titleDirty]);
  const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:6}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));
  const move=(n:Note,columnId:string,beforeId?:string)=>{void submit('note.move',{id:n.id,generation:n.generation,columnId,beforeId});setAnnouncement(`${n.title} moved to ${columns.find(c=>c.id===columnId)?.title}.`);};
  return <><div className="kanban-controls"><label>Go to column<select aria-label="Go to column" onChange={e=>document.getElementById(`column-${e.target.value}`)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest',inline:'start'})}><option value="">Choose a column</option>{columns.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>{editable&&<button onClick={()=>setManage(!manage)} className="lab-button secondary">Manage columns</button>}<button className="lab-button secondary" onClick={()=>setTrash(!trash)}><Trash2 size={16}/>Note trash</button>{lastDeleted&&editable&&<button className="lab-button secondary" onClick={()=>{void submit('note.restore',{id:lastDeleted.id,generation:lastDeleted.generation,columnId:lastDeleted.columnId});setLastDeleted(undefined);}}><RotateCcw size={16}/>Undo delete</button>}</div>
    {manage&&editable&&<section className="column-manager" aria-label="Manage columns"><form onSubmit={e=>{e.preventDefault();if(columnTitle.trim()){void submit('column.create',{id:crypto.randomUUID(),title:columnTitle});setColumnTitle('');}}}><input aria-label="New column name" placeholder="New column name" value={columnTitle} onChange={e=>setColumnTitle(e.target.value)} maxLength={200}/><button className="lab-button secondary">Add column</button></form>{columns.map((c,index)=><div key={c.id}><span>{c.title}</span><button disabled={!index} aria-label={`Move ${c.title} earlier`} onClick={()=>void submit('column.move',{id:c.id,beforeId:columns[index-1].id})}><ArrowLeft size={16}/></button><button disabled={index===columns.length-1} aria-label={`Move ${c.title} later`} onClick={()=>void submit('column.move',{id:c.id,beforeId:columns[index+2]?.id})}><ArrowRight size={16}/></button><button aria-label={`Delete ${c.title}`} onClick={()=>{setDeleteColumn(c);setTarget(columns.find(x=>x.id!==c.id)?.id||'');setDeleteAction(columns.length>1?'move':'trash');}}><Trash2 size={16}/></button></div>)}</section>}
    {trash&&<section className="note-trash" aria-label="Deleted notes"><h2>Deleted notes</h2>{resource.data.notes.filter(n=>n.deletedAt).map(n=><div key={n.id}><span>{n.title}</span>{editable&&<button disabled={!columns.length} onClick={()=>void submit('note.restore',{id:n.id,generation:n.generation,columnId:columns.find(c=>c.id===n.columnId)?.id||columns[0]?.id})}>Restore</button>}</div>)}</section>}
    <div className={`kanban-workspace ${note?'with-inspector':''}`}><DndContext sensors={sensors} collisionDetection={closestCorners} onDragStart={e=>setActive(String(e.active.id))} onDragCancel={()=>{setActive(undefined);setAnnouncement('Move canceled.');}} onDragEnd={e=>{setActive(undefined);const n=notes.find(n=>n.id===e.active.id);if(!n||!e.over||e.active.id===e.over.id)return;const overNote=notes.find(n=>n.id===e.over!.id),overColumn=columns.find(c=>c.id===e.over!.id);if(overNote)move(n,overNote.columnId,overNote.id);else if(overColumn)move(n,overColumn.id);}} accessibility={{announcements:{onDragStart:({active})=>`Picked up ${notes.find(n=>n.id===active.id)?.title}. Use arrow keys to move, Space to drop, Escape to cancel.`,onDragCancel:()=>'Move canceled.',onDragEnd:()=>announcement,onDragOver:({over})=>over?`Over ${notes.find(n=>n.id===over.id)?.title||columns.find(c=>c.id===over.id)?.title}`:undefined}}}>
      <div className="kanban-columns">{columns.map(c=><ColumnView key={c.id} column={c} notes={notes.filter(n=>n.columnId===c.id)} models={getModel} editable={editable} submit={submit} select={setSelected} selected={selected} active={active}/>)}</div><DragOverlay dropAnimation={reduced?null:{duration:140,easing:'ease-out'}}>{active&&<div className="sticky-note drag-overlay"><strong>{notes.find(n=>n.id===active)?.title}</strong></div>}</DragOverlay>
    </DndContext>
    {note&&<aside className="note-inspector" aria-label="Note settings"><header><h2>Note settings</h2><button aria-label="Close note settings" onClick={()=>setSelected(undefined)}><X size={18}/></button></header><label>Title<input aria-label="Note title" value={title} readOnly={!editable} maxLength={200} onChange={e=>{if(!titleDirty)baseTitle.current=note.versions.title;setTitleDirty(true);setTitle(e.target.value);}} onBlur={()=>{if(titleDirty&&editable){void submit('note.field',{id:note.id,generation:note.generation,field:'title',value:title,baseVersion:baseTitle.current});setTitleDirty(false);}}}/></label><label>Body<CollaborativeBody model={getModel(note)} label="Sidebar note body" readOnly={!editable}/></label><fieldset disabled={!editable}><legend>Note color</legend><div className="note-colors">{colors.map(color=><button key={color} className={`note-${color}`} aria-label={`${color} note`} aria-pressed={note.color===color} onClick={()=>void submit('note.field',{id:note.id,generation:note.generation,field:'color',value:color,baseVersion:note.versions.color})}>{color}</button>)}</div></fieldset><label>Column<select aria-label="Note column" value={note.columnId} disabled={!editable} onChange={e=>move(note,e.target.value)}>{columns.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>{editable&&<><div className="note-movement"><button onClick={()=>{const list=notes.filter(n=>n.columnId===note.columnId),index=list.findIndex(n=>n.id===note.id);if(index>0)move(note,note.columnId,list[index-1].id);}}><ArrowUp size={16}/>Earlier</button><button onClick={()=>{const list=notes.filter(n=>n.columnId===note.columnId),index=list.findIndex(n=>n.id===note.id);if(index<list.length-1)move(note,note.columnId,list[index+2]?.id);}}><ArrowDown size={16}/>Later</button></div><button className="note-delete" onClick={()=>{setLastDeleted(note);void submit('note.delete',{id:note.id,generation:note.generation});setSelected(undefined);}}><Trash2 size={16}/>Delete note</button></>}</aside>}
    </div><p className="sr-only" role="status">{announcement}</p>
    {deleteColumn&&<div className="collab-modal-backdrop"><div ref={dialog} className="collab-dialog" role="dialog" aria-modal="true" aria-labelledby="column-delete-title"><h2 id="column-delete-title">Delete {deleteColumn.title}?</h2><p>{notes.filter(n=>n.columnId===deleteColumn.id).length} notes will be affected. Deleted content stays recoverable.</p><label>Handle notes<select value={deleteAction} onChange={e=>setDeleteAction(e.target.value)}><option value="move" disabled={columns.length<2}>Move notes</option><option value="trash">Move notes to trash</option></select></label>{deleteAction==='move'&&<label>Destination<select value={target} onChange={e=>setTarget(e.target.value)}>{columns.filter(c=>c.id!==deleteColumn.id).map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>}<button className="lab-button secondary" onClick={()=>setDeleteColumn(undefined)}>Cancel</button><button className="lab-button primary" onClick={()=>{void submit('column.delete',{id:deleteColumn.id,action:deleteAction,targetId:target});setDeleteColumn(undefined);}}>Delete column</button></div></div>}
  </>;
}
