import { useEffect,useState } from 'react';
import WorkspaceGate from '../collaboration/WorkspaceGate';
import { request,workspaceId,endpoint } from '../../utils/collaboration/client';
import { download } from '../../utils/collaboration/export';
import type { Workspace } from '../../types/collaboration';
import '../../design/collaboration.css';
function Settings({workspace}:{workspace:Workspace}) {
  const [folder,setFolder]=useState(''),[message,setMessage]=useState(''),[jobs,setJobs]=useState<any[]>([]),[busy,setBusy]=useState(false);
  const load=async()=>{try{const [settings,list]=await Promise.all([request(`/api/drive-settings?workspace=${workspace.id}`),request(`/api/drive-checkpoints?workspace=${workspace.id}`)]);setFolder(settings.destination?.folder_id||'');setJobs(list.checkpoints);}catch(e){setMessage((e as Error).message);}};
  useEffect(()=>{void load();},[]);
  const get=async(id:string)=>{const result=await request(`/api/drive-checkpoints?workspace=${workspace.id}&download=${id}`);return result.snapshot;};
  const recover=async(id:string)=>{setBusy(true);try{const snapshot=await get(id);const kind=snapshot.type==='excalidraw'?'drawing':snapshot.type==='sample-logger-kanban'?'board':undefined;if(!kind)throw new Error('Unsupported checkpoint.');const importData=kind==='drawing'?{columns:[],notes:[],elements:snapshot.elements,files:snapshot.files||{}}:snapshot.resource.data;const resourceId=crypto.randomUUID();await request(endpoint(),{workspaceId:workspace.id,operation:{id:crypto.randomUUID(),resourceId,generation:1,type:'resource.create',payload:{kind,name:`Recovered ${kind} ${new Date().toLocaleDateString()}`,importData},createdAt:new Date().toISOString()}});setMessage(`Recovered a new ${kind}. Open Shared ${kind==='board'?'boards':'drawings'} to review it.`);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  return <section className="drive-destination"><h2>Shared workspace Drive backups</h2><p>Application membership controls shared editing. Existing Drive folder permissions control who can read exported files. Previews are for viewing; multiplayer editing happens here. Folder sharing is never changed automatically.</p>{workspace.role==='admin'&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const result=await request(`/api/drive-settings?workspace=${workspace.id}`,{workspaceId:workspace.id,folderId:folder});setMessage(result.message);}catch(err){setMessage((err as Error).message);}finally{setBusy(false);}}}><label htmlFor="drive-folder">Destination folder ID</label><input id="drive-folder" value={folder} onChange={e=>setFolder(e.target.value)} placeholder="Dedicated Shared Drive folder ID"/><button className="lab-button secondary" disabled={busy}>Validate and configure folder</button></form>}<p role="status">{message||'Live Drive saving has not been verified for this workspace.'}</p><button onClick={()=>void load()}>Refresh checkpoint status</button><ul>{jobs.map(job=><li key={job.id}>Revision {job.revision} · {job.status} {job.error&&<span>{job.error}</span>}{job.status==='saved'&&<><button onClick={async()=>{try{download(`checkpoint-r${job.revision}.json`,JSON.stringify(await get(job.id)));}catch(e){setMessage((e as Error).message);}}}>Download</button>{workspace.role!=='viewer'&&<button disabled={busy} onClick={()=>void recover(job.id)}>Recover as new resource</button>}</>}{['failed','pending'].includes(job.status)&&workspace.role!=='viewer'&&<button onClick={async()=>{try{const result=await request(`/api/drive-checkpoints?workspace=${workspaceId()}`,{workspaceId:workspaceId(),resourceId:job.resource_id,jobId:job.id});setMessage(result.message);}catch(e){setMessage((e as Error).message);}}}>Retry checkpoint</button>}</li>)}</ul></section>;
}
export default function DriveDestination(){return <WorkspaceGate>{workspace=><Settings workspace={workspace}/>}</WorkspaceGate>;}
